### ISSUE TITLE
Allow Mods to use Northstar to read/write to files within their respective directories

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarLauncher#11]
This would allow mods to save data, allowing for better banlists, and other functions. Since there doesn't seem to be a way to do this due to Respawn's modification of Squirrel, the easiest option is probably to add the functions here similarly to how functions like NSSetModEnabled work

**Comment by pg9182** [comment]
If this is implemented, there should be an option to store all data in a separate folder to make data persistence easier for container images.

It would be even better if a K/V interface was exposed instead of files, and if NorthstarLauncher allowed forwarding read/update/delete requests to a separate Redis server. This would allow it to work correctly in clustered configurations.

**Comment by ASpoonPlaysGames** [comment]
issue #11 and it's still being actively discussed, pain
