### ISSUE TITLE
Unable to play in multiplayer mode

### ISSUE THREAD

**Issue by Twaimchencer** [R2Northstar/NorthstarLauncher#123]
How to solve it? It has been updated to the latest version.
![未命名](https://user-images.githubusercontent.com/102529225/160405877-8897f4ec-5b88-4c6b-b685-1ec5fe0877e6.jpg)

**Comment by GeckoEidechse** [comment]
Northstar MasterServer is down due to security issues with the base game [as described here](https://github.com/R2Northstar/Northstar/issues/124#issuecomment-1073206536) and the [Northstar Discord](https://northstar.tf/discord).

Will be playable again once we release an update for Northstar (likely some time this week).

**Comment by ButterNm1lk** [comment]
i can't wait to play :)
