### ISSUE TITLE
dedicated: Add option to disable logging to a file

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/NorthstarLauncher#52]
This is not needed when running within a container since logs will be read from stdout/stderr and managed by the host.

**Comment by pg9182** [comment]
Oops, I accidentally duplicated my own issue #23.

**Comment by abarichello** [comment]
lol

**Comment by pg9182** [comment]
Actually, no, that isn't what I'm looking for, I think.

**Comment by pg9182** [comment]
I still need stdout logs, and iirc, those go through spdlog.

**Comment by emma-miler** [comment]
I think it'd be good to adopt the standard model of always writing to a `latest.log` and writing to a datetime-coded log if explicit logging is enabled. In my latest PR i added a `configurables.cpp`, which could easily be extended to include other command line flags such as this.

**Comment by GeckoEidechse** [comment]
> I think it'd be good to adopt the standard model of always writing to a `latest.log` and writing to a datetime-coded log if explicit logging is enabled.

I'd argue in that case, simply periodically cleaning old logs if directory size grows larger than some pre-defined value makes more sense. Otherwise we'll have scenarios like: game crashes due to some bug -> restart game cause you wanna play rn -> make issue about previous bug -> log gone.

This should however exist next to the option of completely disabling logging (logging to file should still be on by default).

**Comment by emma-miler** [comment]
That's not a bad idea. Maybe we could implement a log rotation or something. In any case, if the other PR gets merged, I'll add the option to completely disable logging.
