### ISSUE TITLE
[Windows 7] Crash on startup: "The procedure entry point CreateFile2 could not be located in the dynamic link library KERNEL32.dll"

### ISSUE THREAD

**Issue by Gazyi** [R2Northstar/NorthstarLauncher#612]
It crashes since build `1.20.0-rc1`, probably because of minizip lib which uses this function ([mz_os_win32.c#L206](https://github.com/zlib-ng/minizip-ng/blob/680d6f1dcf9de99fc033b54975a1dfff10be2b6b/mz_os_win32.c#L206), [mz_strm_os_win32.c#L106](https://github.com/zlib-ng/minizip-ng/blob/680d6f1dcf9de99fc033b54975a1dfff10be2b6b/mz_strm_os_win32.c#L106)).

**Comment by GeckoEidechse** [comment]
Good catch and thanks for the report <3

Thing is, I don't think we are willing to revert the change as it's needed for mod-auto-download which will become an integral part of Northstar in the near future.

Windows 7 has been EoL for over 3 years and Steam Hardware survey puts it at _0.8%_ of all Windows users so I'm not sure if it's worth the [opportunity cost](https://en.wikipedia.org/wiki/Opportunity_cost) to investigate a fix that also works for Windows 7.

Of course, if someone wants to PR a change that addresses it, I'll gladly take it but otherwise I think it might be just to much effort for too little impact.

(Sidenote: Yes Windows 10 sucks, so does every version of Windows. Linux is the way to go <3)

**Comment by Alystrasz** [comment]
Could you give us an error message?
Maybe the problem does not come from minizip itself but from one of its dependencies?
(we're looking into removing some [here](https://github.com/R2Northstar/NorthstarLauncher/pull/602))

**Comment by GeckoEidechse** [comment]
Closing as stale due to the lack of response. Windows 7 support is not a priority as the userbase is tiny and continues to decrease (0.5% on Steam HW survey atm).

We simply cannot afford spending time on something that on the scale of Northstar only affects around 2-3 people.
If Windows 10+ telemetry is an issue for you and the reason you stick to Windows 7, then I highly recommend switching to Linux instead. Linux playerbase on Northstar is higher than Windows 7 and as such gets priority when comparing the two.

We still accept PRs that improve Windows 7 support granted they do not negatively affect the rest of the playerbase or code quality, however we will not actively work on improving Windows 7 support as there are other areas that will benefit a larger chunk of players.

**Comment by L688944** [comment]
power bi open  problem the procedure entry point create files2 could not be locted in the dynamic link kernel32dll

**Comment by L688944** [comment]
reply me
