### ISSUE TITLE
clang-cl support

### ISSUE THREAD

**Issue by Jan200101** [R2Northstar/NorthstarLauncher#713]
Needed for clang-cl to work:
- #706

clang-cl can be installed via the Visual Studio Installer or from your distro package manager.
On Linux you also need the all the libraries and headers which can be downloaded via [msvc-wine](https://github.com/mstorsjo/msvc-wine) (do note that there are some library not found errors that I will work on fixing).

wsock32 proxy is broken due to https://github.com/llvm/llvm-project/issues/43865 with at least clang 18.1.6 but appears fixed on the master branch

**Comment by GeckoEidechse** [comment]
Before anyone is gonna start commenting on how we shouldn't move away from the compiler that Titanfall2 was compiled with (MSVC), I wanna stress again that the intention here is to **additionally** support other compilers.

Why? Cause different compilers produce different warnings due to differing in their implementation. So by compiling Northstar with different compilers and checking warning (and error) outputs, we get greater coverage in catching potential bugs :eyes:

**Comment by Jan200101** [comment]
There is also the fact that MSVC isn't the most reliable (as we have seen with the 1.24.5 release) so a sane fallback would help in many ways.

**Comment by Jan200101** [comment]
completed
